#pragma once

#define REAL_MOUSE_BUTTON_1         0
#define REAL_MOUSE_BUTTON_2         1
#define REAL_MOUSE_BUTTON_3         2
#define REAL_MOUSE_BUTTON_4         3
#define REAL_MOUSE_BUTTON_5         4
#define REAL_MOUSE_BUTTON_6         5
#define REAL_MOUSE_BUTTON_7         6
#define REAL_MOUSE_BUTTON_8         7
#define REAL_MOUSE_BUTTON_LAST      REAL_MOUSE_BUTTON_8
#define REAL_MOUSE_BUTTON_LEFT      REAL_MOUSE_BUTTON_1
#define REAL_MOUSE_BUTTON_RIGHT     REAL_MOUSE_BUTTON_2
#define REAL_MOUSE_BUTTON_MIDDLE    REAL_MOUSE_BUTTON_3